### ISSUE TITLE
img

### ISSUE THREAD

**Issue by jaybdub** [NVIDIA-AI-IOT/trt_pose#1]
![image](https://user-images.githubusercontent.com/4212806/67124387-4c183c80-f1a7-11e9-8125-05738898e030.png)

**Comment by FrancisLeung** [comment]
Hi John,
Can you tell me how to troubleshoot the following error on Jupyter notebook when I tried to run trt_pose project please?
1) Error: No "trt_pose.coco"
2) AttributeError Traceback (most recent call last)
<ipython-input-5-6086db02bdd7> in <module>()
3 MODEL_WEIGHTS = 'resnet18_baseline_att_224x224_A_epoch_249.pth'
4
----> 5 model.load_state_dict(torch.load(MODEL_WEIGHTS))

AttributeError: 'module' object has no attribute 'load_state_dict'

Thanks,
Francis

**Comment by COBECTb** [comment]
can't download model file
