### ISSUE TITLE
Low FPS than report in Jetson nano

### ISSUE THREAD

**Issue by tucachmo2202** [NVIDIA-AI-IOT/trt_pose#115]
Hi, 
I highly appreciate your repo. But I test your model in Jetson nano Tegra X1 it just got about 8FPS lower than 22 FPS in your report. I just follow your guide except I did not use USB camera, I used OpenCV to read image instead of. I want to know whether you use other kind of Jetson nano, which version of Pytorch or I made a mistake. Many tks.

**Comment by twmht** [comment]
I have the same issue.

**Comment by tucachmo2202** [comment]
@twmht I guess the author calculate with small cmap_window and quite small max_num_objects.

**Comment by alessandrolombardini** [comment]
I have the same issue, I think. With resnet I reached only 6 FPS. I used the notebook given so it's quite strange that I can't get the same results of authors using the same environment.
