### ISSUE TITLE
Can't download weights

### ISSUE THREAD

**Issue by Drallert** [NVIDIA-AI-IOT/trt_pose#127]
When trying to download weights for resnet18_baseline_att_224x224_A and densenet121_baseline_att_256x256_B models, Google Drive says that the files are not available temporarily. I'll attach screenshots:

Resnet18
![Captura de pantalla de 2021-05-12 12-52-45](https://user-images.githubusercontent.com/38808659/117963812-1efb2400-b321-11eb-870d-1c637ae0efcd.png)

Densenet121
![Captura de pantalla de 2021-05-12 12-52-59](https://user-images.githubusercontent.com/38808659/117963770-1276cb80-b321-11eb-854b-77f13365c5b6.png)

**Comment by Drallert** [comment]
I've been able to download the resnet model, thanks and sorry for the inconvenience

**Comment by helloyuning** [comment]
> I've been able to download the resnet model, thanks and sorry for the inconvenience

Can you share the weight? Now it is not accessible...

**Comment by KevinHuge** [comment]
> > I've been able to download the resnet model, thanks and sorry for the inconvenience
> 
> Can you share the weight? Now it is not accessible...

Have you obtained the weights of the model? I can't access the weights either...

<img width="2180" height="1142" alt="Image" src="https://github.com/user-attachments/assets/29a2bb6c-0e51-4d5a-9a22-a658a66e5061" />
