### ISSUE TITLE
How to get x, y coordinates of neck?  

### ISSUE THREAD

**Issue by Amyhds** [NVIDIA-AI-IOT/trt_pose#135]
I want to see the changes of coordinates of neck. 
How can I get these?

**Comment by pramod-wick** [comment]
Hi,

you can follow the code given in this blog of using trt-pose (works on pc or jetson device). Specially use the "get_keypoint" function to extract keypoints of any joint.
 
[https://spyjetson.blogspot.com/2019/12/jetsonnano-human-pose-estimation-using.html](url)

**Comment by Amyhds** [comment]
> Hi,
> 
> you can follow the code given in this blog of using trt-pose (works on pc or jetson device). Specifically use the "get_keypoint" function to extract keypoints of any joint.
> 
> https://spyjetson.blogspot.com/2019/12/jetsonnano-human-pose-estimation-using.html

Thank you so much

**Comment by Amyhds** [comment]
There's something wrong with opencv....I got some errors...
