### ISSUE TITLE
How can I train trt_pose on multi-GPU?

### ISSUE THREAD

**Issue by kinglintianxia** [NVIDIA-AI-IOT/trt_pose#39]
@jaybdub
Hi, jaybdub, Thanks for your great work! 
When I was trainning the net, I find the trainning process on only one GPU(I have two),  how can I train trt_pose on multi-GPU? And restore from a pretrained checkpoint?

**Comment by AllenDun** [comment]
this repo not support multi-gpu trainning now?

**Comment by kinglintianxia** [comment]
> this repo not support multi-gpu trainning now?
I used to train on a  machine with two 1080ti, only gpu: 0 used in the training, have you tried it?

**Comment by kinglintianxia** [comment]
Finally I solved this.

**Comment by jpapon** [comment]
For reference, I just added:
`model = torch.nn.DataParallel(model)`
after the amp initialization in `train.py` and it uses multiple gpus.
It looks like I'm now constrained by the data loader though, so I don't think that's being parallelized properly.
@kinglintianxia did you do anything else for this?
