### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by jgoldm** [NVIDIA-AI-IOT/trt_pose#66]
This error is caused by an update to torch2trt. I was able to fix it by using a version of torch2trt from a month ago.

When I run `model_trt = torch2trt.torch2trt(model, [data], fp16_mode=True, max_workspace_size=1<<25)` in the live demo I get the following error:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-ed7837f7f2b5> in <module>
      1 import torch2trt
      2 
----> 3 model_trt = torch2trt.torch2trt(model, [data], fp16_mode=True, max_workspace_size=1<<25)

/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py in torch2trt(module, inputs, input_names, output_names, log_level, max_batch_size, fp16_mode, max_workspace_size, strict_type_constraints, keep_network, int8_mode, int8_calib_dataset, int8_calib_algorithm, int8_calib_batch_size, use_onnx)
    500             ctx.add_inputs(inputs, input_names)
    501 
--> 502             outputs = module(*inputs)
    503 
    504             if not isinstance(outputs, tuple) and not isinstance(outputs, list):

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    489             result = self._slow_forward(*input, **kwargs)
    490         else:
--> 491             result = self.forward(*input, **kwargs)
    492         for hook in self._forward_hooks.values():
    493             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py in forward(self, input)
     95     def forward(self, input):
     96         for module in self._modules.values():
---> 97             input = module(input)
     98         return input
     99 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    489             result = self._slow_forward(*input, **kwargs)
    490         else:
--> 491             result = self.forward(*input, **kwargs)
    492         for hook in self._forward_hooks.values():
    493             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/trt_pose-0.0.1-py3.6-linux-aarch64.egg/trt_pose/models/resnet.py in forward(self, x)
     17         x = self.resnet.maxpool(x)
     18 
---> 19         x = self.resnet.layer1(x) # /4
     20         x = self.resnet.layer2(x) # /8
     21         x = self.resnet.layer3(x) # /16

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    489             result = self._slow_forward(*input, **kwargs)
    490         else:
--> 491             result = self.forward(*input, **kwargs)
    492         for hook in self._forward_hooks.values():
    493             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py in forward(self, input)
     95     def forward(self, input):
     96         for module in self._modules.values():
---> 97             input = module(input)
     98         return input
     99 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    489             result = self._slow_forward(*input, **kwargs)
    490         else:
--> 491             result = self.forward(*input, **kwargs)
    492         for hook in self._forward_hooks.values():
    493             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torchvision/models/resnet.py in forward(self, x)
     53             identity = self.downsample(x)
     54 
---> 55         out += identity
     56         out = self.relu(out)
     57 

/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py in wrapper(*args, **kwargs)
    281 
    282             #             print('%s' % (converter.__name__,))
--> 283             converter["converter"](ctx)
    284 
    285             # convert to None so conversion will fail for unsupported layers

/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/converters/add.py in convert_add(ctx)
     12     output = ctx.method_return
     13     input_a_trt, input_b_trt = add_missing_trt_tensors(ctx.network, [input_a, input_b])
---> 14     input_a_trt, input_b_trt = broadcast_trt_tensors(ctx.network, [input_a_trt, input_b_trt], output.ndim - 1)
     15     layer = ctx.network.add_elementwise(input_a_trt, input_b_trt, trt.ElementWiseOperation.SUM)
     16     output._trt = layer.get_output(0)

AttributeError: 'Tensor' object has no attribute 'ndim'
`

**Comment by chealyte** [comment]
how do you fix this ? i got this error too .. i could not figure out how to fix it ..

**Comment by jaybdub** [comment]
Hi jgoldim,

Thanks for reaching out!

This was due to in an update in torch2trt which broke with older versions of PyTorch.

I've added a fix in the master branch of torch2trt, you should be able to re-install and no longer face this issue :)

Please let me know if this helps or you run into any trouble.

Best,
John
