### ISSUE TITLE
Only select the person closest to the camera

### ISSUE THREAD

**Issue by mcdonasd** [NVIDIA-AI-IOT/trt_pose#98]
Has anyone modified this solution to only detect the person closest to the camera?

**Comment by mcdonasd** [comment]
Is the solution as easy as the following?
```
counts, objects, peaks = parse_objects(cmap, paf)

if int(counts) == 1:
      draw_objects(image, counts, objects, peaks)
```

**Comment by cwlinghk** [comment]
> Is the solution as easy as the following?
> 
> ```
> counts, objects, peaks = parse_objects(cmap, paf)
> 
> if int(counts) == 1:
>       draw_objects(image, counts, objects, peaks)
> ```
counts is the number of detected people.
Your case would just draw the skeleton if there is one people detected.
I guess you have to calculate the area of the bounding box, find maximum, and select the people to draw

**Comment by mcdonasd** [comment]
Thank you!  This helps.

**Comment by djramakrishna** [comment]
Hey @mcdonasd  I'm looking for something very similar. I want to make sure it detects only one person per frame (which has teh highest confidence score) and return only one value for each key-point in that particular frame. Please let me know if you've solved this issue.
